### ISSUE TITLE
Researching Date recognition

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-docs#11]
We have a problem - we need to find out the Publication date of articles we locate in some generalized way. Is this possible? If so, how would we do it?

**Comment by kstapelfeldt** [comment]
Review this: https://github.com/mediacloud/date_guesser to see if we can repurpose it. If we use it, where in the stack would we deploy this technology?

**Comment by kstapelfeldt** [comment]
This remains as a task to review.

**Comment by kstapelfeldt** [comment]
https://www.labnol.org/internet/search/find-publishing-date-of-web-pages/8410/

**Comment by amygao9** [comment]
Another python library we are currently looking into is https://pypi.org/project/articleDateExtractor/
It claims to have 90% success rate and seems to be more developed than the media cloud date guesser.

**Comment by kstapelfeldt** [comment]
Okay. I was thinking of how we might leverage Google for articles https://www.labnol.org/internet/search/find-publishing-date-of-web-pages/8410/ or to fill in gaps, but this won't work programatically.

**Comment by kstapelfeldt** [comment]
Amy and Jacqueline looked into the two projects. Jacqueline wrote a script to test the two. Jacqueline spent the past week on this. She looked into the google solution kirsta sent in the chat - we would probably need to use Google's API. When she was trying to install it she realized there was a limit of searches (100 per day). Limits the usability of this method. Nat had found a python library that Jacqueline also looked at - it is the best one so far. However, Jacqueline has found more than one (there's one from Amy linked above). She will stick with the one we linked earlier. Also looking into Javascript libraries because they are not maintained. Jacqueline discussed with Nat - Jacqueline and Raiyan to make a decision together about this by Friday.  Present next Tuesday's meeting.

**Comment by jacqueline-chan** [comment]
This can be closed. It is decided that we will use the Metascraper as our publishing date source. 
https://www.npmjs.com/package/metascraper
