### ISSUE TITLE
Upgrade Sudo for all instances on compute canada

### ISSUE THREAD

**Issue by jacqueline-chan** [UTMediaCAT/mediacat-docs#15]
Graham x2
Arbutus x3

**Comment by jacqueline-chan** [comment]
![image](https://user-images.githubusercontent.com/24948588/106303551-4160aa00-6228-11eb-8fd5-4248524b9ddf.png)
Install GRUB

**Comment by jacqueline-chan** [comment]
![image](https://user-images.githubusercontent.com/24948588/106306857-9bfc0500-622c-11eb-8306-c0f04d24bd96.png)


https://help.ubuntu.com/community/Grub2/Upgrading

**Comment by jacqueline-chan** [comment]
Graham 
- [x]  instance 1
- [x]  instance 2

Arbutus
- [x] instance 1
- [x] instance 2
- [x] instance 3

**Comment by kstapelfeldt** [comment]
We should prioritize the update. @amygaoo will kill active processes she has going. Graham instance 2 is still running crawler.
