### ISSUE TITLE
Create coding standards document for use in the project

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-docs#4]
- Tests & Comment format
- Design repository structure and document
- Consider separate repositories for separate components
- Author standards as an .md

**Comment by RaiyanRahman** [comment]
It has been uploaded to the root folder of the mediacat-docs repo.
[https://github.com/UTMediaCAT/mediacat-docs/blob/master/coding_standards.md](https://github.com/UTMediaCAT/mediacat-docs/blob/master/coding_standards.md)
