### ISSUE TITLE
Twitter Crawler Code

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-docs#5]
https://github.com/UTMediaCAT/Voyage/blob/master-conversion/src/twitter_crawler.py

Review for currency/approach. Re-write in contemporary python, including tests and following coding standards. 

Crawler should, given a list of user handles in .csv grab all possible twarc output and store in a file.

**Comment by kstapelfeldt** [comment]
https://github.com/twintproject/twint is the project that will meet all the stated requirements for crawling all tweets over time. However, a recent change has caused the code to break. The current code maintainer is likely to update this as many people use the project. The developer has an active branch that Danhua is testing.

**Comment by kstapelfeldt** [comment]
We will wait a week and see if there is action on the broken portion of the TWINT stack and then test it for its functionality in our code.

**Comment by kstapelfeldt** [comment]
This should be working soon based on Danhua's interaction with the developer.

**Comment by kstapelfeldt** [comment]
Danhua will look into puppeteer as a solution for crawling twitter 
May need to log in as a user

* https://www.npmjs.com/package/twitter-puppeteer https://blog.usejournal.com/exploring-the-power-of-puppeteer-903a1c8c137b
* https://www.npmjs.com/package/twitter-puppeteer

**Comment by kstapelfeldt** [comment]
The owner of getoldtwitter has a working codebase and has sent a video to Danhua. Tonight he will teach Danhua how to use it and she will clarify how to integrate it into the project. Python 3 work.

**Comment by kstapelfeldt** [comment]
Remaining encoding issue - small formatting issue still to be dealt with. snscrape is the library we are using: https://github.com/JustAnotherArchivist/snscrape

**Comment by kstapelfeldt** [comment]
Remaining issue: the current crawler is IP blocked - between 4,000-10,000 will trigger the block. Nat suggestions are 1: developing a timing mechanism delay so that each request will have a delay. For example, you make one request and give it 30 second before making the second request. If this doesn't work we will have to consider some kind of IP switching.  Limit requests per day.

**Comment by kstapelfeldt** [comment]
Ongoing IP issues, so we moved back to TWINT. It doesn't use API but can return all tweets from a given user. Output file is quite clean. Please push code to twitter crawler and make this repo private. Then this ticket can be closed.

**Comment by kstapelfeldt** [comment]
Danhua will take twitter .csv outputs and keep them (for us to discuss with Alejandro re: the extra data like 'hit counts'). She will then concatenate the output CSVs and reshape with the following columns:

- source URL
- Unique ID
- Title
- Author Metadata
- Twitter Handle
- Date
- HTML content
- Plain Text Content
- List of links reference

**Comment by jacqueline-chan** [comment]
- New Feature: Given a specific time line, the twitter crawler should return the tweets based on it's date.

**Comment by kstapelfeldt** [comment]
## Remaining to do

1. Add columns for the rest of the data that we get back from TWINT.
2. Add in some handling for errors and interruptions on the crawl. 

--> We need a mechanism to make sure we are notified as to the status of the crawl or if things are interrupted. 
--> How do we add more resilience or handle interruptions? 
--> Key errors to handle are exit errors - we don't want the crawler to cut off and then the crawl is interrupted. 

Screenshot of relevant error attached

![image (5)](https://user-images.githubusercontent.com/467898/98025749-7d7a9f00-1de0-11eb-92a5-dfce4b8dce82.png)

**Comment by jacqueline-chan** [comment]
Here is the full output of the exit signal.
Note: this does not happen every time. Only sometimes.
[output.txt](https://github.com/UTMediaCAT/mediacat-docs/files/5489843/output.txt)

**Comment by jacqueline-chan** [comment]
This is what a connection error looks like, and may stop the whole crawl if exit signal received. 
![image](https://user-images.githubusercontent.com/24948588/98304957-f4ee3100-1f8e-11eb-8baf-03249c41e401.png)

**Comment by kstapelfeldt** [comment]
* Enhance to accept a variable for time (define a period of time to be crawled)
*  One more function accept a variable for keywords

**Comment by jacqueline-chan** [comment]
Potential bug?

![image](https://user-images.githubusercontent.com/24948588/99846586-986d4300-2b44-11eb-856a-6e13ef9a9c43.png)
