### ISSUE TITLE
MediaCat-Domain-Crawler

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-docs#6]
https://github.com/puppeteer/puppeteer/tree/v5.3.0 is overall the better project, but does not allow for a workaround for this site: http://elderofziyon.com/ which returns an empty JSON list using puppeteer while Selenium lets us work around this. For now, don't worry about this edge case. Puppeteer also resolves the issue of pop-ops. 

1. please commit the code to the new mediacat-domain-crawler repository. 
2. test crawling these ten domains

- nytimes.com
- algemeiner.com
- jewishjournal.com
- christianitytoday.com
- washingtonpost.com
- electronicintifada.net
- cjr.org
- foxnews.com
- mondoweiss.net
- al-monitor.com

Output: Sample data that can be used to start developing the parser (limit to 10-20 results) and put this into a folder in dev-docs

3. need to discuss and update this diagram: 

https://padlet.com/kirstastapelfeldt/sm88l9hv1rzy5ezx ...where are new URLs within the domain discovered and crawled? Currently it looks like the code does this as part of the crawler, and the diagram has this as part of the data parser. In order to discover the URL, you will have to parse it. Is this because of a function in puppeteer?

**Comment by kstapelfeldt** [comment]
Related to ticket https://github.com/UTMediaCAT/mediacat-domain-crawler/issues/3

#1 Raiyan to do a sample crawl of several domains 10-20 articles deep and export data as a .csv or other file (JSON). As close to sample output as possible from this document: https://docs.google.com/spreadsheets/d/1DJfiLT7XGL0XXttp8q0BKRZkn6swWAQ74gdlcaYG3CI/edit#gid=1389576919 recognizing that there is more post-processing that would need to be done. 

#2 Raiyan to work with Alexandru to discuss how to implement filtering of the queue to support the task that Alex has worked on as well as the task of identifying what are relevant news items to crawl. We also need to store domains and twitter users that are referenced, but not part of the original scope for later display to a user.

**Comment by kstapelfeldt** [comment]
Raiyan  got the filter function that Alex wrote integrated into his code and demoed a crawl. Filtering function has stored all links outside domain. 

Question re: Queue - stored in same root folder. This folder contains subfolders for every single to be crawled link. As the crawler goes through each site, it deletes the relevant folder. If the crawler is interrupted, then it would restart on the folders that were not yet crawled. 

Overall approach will be to handle cruft in post-processing. This task is mostly complete pending integration with @jacqueline-chan's date detection work.

**Comment by kstapelfeldt** [comment]
@RaiyanRahman needs to push code with included filter and include a couple of tests. This will likely require Travis changes - touch base with @Natkeeran with any questions.

**Comment by kstapelfeldt** [comment]
Midterms!! In addition to the tasks above, we need to push all content to JSON as well as expect an async call from @AlAndr04 's new function.

**Comment by kstapelfeldt** [comment]
Raiyan tested out a couple links but hasn't tested outputs. Most websites can run well. Still bringing back cruft (aggregate pages based on tags, for example). Everything into JSON now. We can see the progress through the JSON. Need to modify the code to accept a .csv from Danhua's parser and then append the regex required to discover all pages.

**Comment by kstapelfeldt** [comment]
- regex stuff done (dynamic regex adding for different domains)
- Ran a test - appears to run quickly and detects every link found on all page and filtered out all links that were outside of domain. Kept data defined by the scope. Data not defined by the scope are in a separate JSON.
- error handling - errors are handled in the crawler. Failed crawls are re-added to the queue. After so many times a URL has been tried, it will be added to a separate file and noted as failed. 

##  Remaining to do

* Accept .csv to populate initial queue (@jacqueline-chan has done initial work in a branch that @RaiyanRahman will review)- migrating to its own ticket
* Adding test cases to the crawler
* Add in some handling for pooling errors? Are there any other errors that will stop the crawl?

**Comment by kstapelfeldt** [comment]
Bugs have emerged where NYT articles were being filtered out. It could be because of PDF changes. Rolled back to prior to the PDF creation. Some instances it works and some where we are filtering articles and links out when we're not supposed to. Still working on it.

**Comment by jacqueline-chan** [comment]
Potentially related to this comment I put here : https://github.com/UTMediaCAT/mediacat-domain-crawler/pull/4#issuecomment-722030665

**Comment by kstapelfeldt** [comment]
@AlAndr04 and @RaiyanRahman determined that the domain was not being updated properly.
@RaiyanRahman added a loop that checks the current link against all scope domain links. Will make it slower, but works for now. 
Merged on Thursday. 

Encountering additional issues @jacqueline-chan will look for debug.log and add to this ticket

**Comment by jacqueline-chan** [comment]
[debug.log](https://github.com/UTMediaCAT/mediacat-docs/files/5555473/debug.log)

**Comment by kstapelfeldt** [comment]
@RaiyanRahman please add back in UUIDs so they can be used by the post-processor - we need one UUID per JSON node (will become the key)

**Comment by kstapelfeldt** [comment]
## To Do

1. Make multiple small JSON files
2. Add back in UUIDs
3. Provide sample "small JSON" to @amygaoo for testing
4. Improve crawler progress reporting by writing the crawler progress (domain - # of URLs crawled) to a .csv at some reasonable interval during the crawling process (every three hours?) @jacqueline-chan will do

@RaiyanRahman should have this done by the end of the week, at which point @jacqueline-chan will update code and re-start crawl on server.

**Comment by RaiyanRahman** [comment]
I have completed 1-3. There are JSON files created for each link crawled now and they are all put in a folder called results. The larger JSON is no longer created. Even if the crawler is continuously running, we can still see the JSONs of all the links that have been crawled meanwhile. The failed links are all still put in a single JSON at the end. We should discuss how to format the failed links in a similar way.

**Comment by kstapelfeldt** [comment]
1. Crawl is currently running. Jacqueline has read the results, and can bring back the number of links crawled. But we don't have domain names or a sense of progress through the whole crawl. @jacqueline-chan is working on this
2. add key for "filtered out links" to the end of each small JSON output file @RaiyanRahman

**Comment by kstapelfeldt** [comment]
@RaiyanRahman didn't get this done last week (he has been testing .csv reader). He thinks he can get it done before the weekend. @jacqueline-chan will hold off on the restart of the crawl until she can merge this change.

**Comment by RaiyanRahman** [comment]
- There is now a key for a list of filtered out links in each smaller JSON. It might be a good idea to remove the larger JSON that is created at the very end as it is storing everything in memory till the end. This might be eating up a lot of memory.

- The bug of empty domains should also be fixed.

**Comment by kstapelfeldt** [comment]
- @RaiyanRahman will remove the large JSON creation process.  Note: the out of scope links will only appear in the small JSON files going forward.

**Comment by kstapelfeldt** [comment]
done but not pushed. Raiyan to push.

**Comment by RaiyanRahman** [comment]
JSON creation process has been removed and changes have been pushed.
